### ISSUE TITLE
Myo simulation and recorder does not work 

### ISSUE THREAD

**Issue by jwaaherr** [MKLab-ITI/MyoWebToolkit#2]
I have downloaded the Myo web tool kit to test my Myo sensor. However, the link available for clients does not work even though it is a chrome browser. I have also downloaded the requirements but I'm not sure how do they come in use. In the folder itself I have tested the recorder and the html file named index for simulation but neither of them work. Is it possible to guide me on how to make this work?

**Comment by jimver04** [comment]
Hi, 

1) index.html is not working ?
    - Is apache server running? Have you installed a XAMPP ?
    - Is port 80 open at your server ? How much familiar are you with ports? Which OS are you using ? Mac, Windows, Linux?
    - What message do you get when you call http://127.0.0.1/MyoWebToolkit/index.html
    - Is port 80 in conflict which another app at server , e.g. Skype? Try changing it to 8080 in httpd.conf. 
    In my local tests I prefer to use 8080 like this
        http://127.0.0.1:8080/MyoWebToolkit/index.html
        
 

2) IndexRecording.html is not working?
    
    - be sure that index.html is running well.
    - have you installed node.js and modules socket.io and express ?
    - have you changed the line 10 in indexRecording.html with your url path ?
         `<base href="http://127.0.0.1:8080/MyoWebToolkit/" />`
    - have you loaded indexRecording.js from command line ? "node indexRecording,js" 
    - Do not close the window of command line because indexRecording.js will stop receiving data      
    -  is port 3000 open at your server?
    - What do you get when you run: 
      http://127.0.0.1:3000

    Test the above and send me the results to see them.

Good Luck,
Dimitrios

**Comment by jwaaherr** [comment]
Hello, 
Thank you for your answer but I actually have no experience in ports or know how to use them. However, I did install an XAMPP and  Node.js but because I have no experience I quite did not understand how to set what you mentioned above, while in note, I'm running on Windows 7.

**Comment by jimver04** [comment]
Hi JA,

1) is your server running?
   There should be an icon "XAMPP Control Panel" in your desktop (if not search it in programs). Run it and press on first line the button "Start" which is in the  "Apache" line. 
a) if it turns green, it is ok. However, there might be a conflict with skype.  Press on "Config" button -> httpd.conf -> Replace "Listen 80" with "Listen 8080". Then restart Apache -> (press "Stop" and "Start" again to restart)
b) otherwise sent the log here.

PS: You do not need Apache, MySQL, FileZilla, Mercury, Tomcat. (Though it would be nice to store information in a MySQL db, but this is a feature to be done in the future).

BR,
Dimitrios

The normal will be like this:

![image](https://cloud.githubusercontent.com/assets/1898502/25472181/d27099e6-2b32-11e7-9108-69954ced05f0.png)

**Comment by jwaaherr** [comment]
Hello, 

I have changed it to 8080 but I still get this message:
![xampp](https://cloud.githubusercontent.com/assets/28006938/25473721/96d78052-2b41-11e7-89fc-9cbf0d49d49a.PNG)

**Comment by jimver04** [comment]
Follow the instructions in here:
http://stackoverflow.com/questions/18300377/xampp-apache-error-apache-shutdown-unexpectedly

**Comment by jwaaherr** [comment]
I think that this will not work because I'm trying to work this out on my university laptop, and the admin might be blocking me from using it? because whenever I try to navigate the httpd-ssl.conf I get this and I cant fix the port number . I will try it using my Mac and see how it will turn out. 
![ssl](https://cloud.githubusercontent.com/assets/28006938/25482511/3e7e036e-2b63-11e7-9285-089a85e62948.PNG)

**Comment by jimver04** [comment]
This is not the httpd.conf !
It is httpd-ssl.conf which is useless in your case.
Try modifying the httpd.conf 

D.

**Comment by jwaaherr** [comment]
yes I have modified it but the link you've sent about the server shutdown also modify the httpd-ssl.conf

**Comment by jimver04** [comment]
ok, I think you should user better an unlocked machine..

**Comment by jwaaherr** [comment]
The Apache server is now running on my Mac, and I've installed Node js. But how can I run "StartNodeServer.bat" on my OS? 

Thank you.

**Comment by jwaaherr** [comment]
hello, 
 I only want the simulation to work and no need for the recorder, and the Apache server is running on my OS. but I quite didn't understand what 'Copy everything to a path visible to web or your local client' means.. can you please tell me what to do next after running my Apache server for the simulation? 

Thank you so much.

**Comment by jimver04** [comment]
Hi,
for the recorder write "sh StartNodeServer.sh" or better "node indexRecording.js"
for the simulator:
copy the code inside the "http" or "httpdocs" or "www". I am not sure which name Apache uses in Mac. Inside these folders, the code can be accessed from Chrome using http://127.0.0.1

BR,
Dimitrios

**Comment by jwaaherr** [comment]
So for the simulator I copy the code  that can be accessed from Chrome, and where shall I put it?

**Comment by jimver04** [comment]
if you are using XAMPP 
     see my previous reponse
else (I assume that you are using the builtin Apache of Mac)
     the folder is "Library > WebServer > Documents"

BR,
Dimitrios

**Comment by jwaaherr** [comment]
hello, 
I couldn't find the web server document in the library. However, I have talked to my advisor about it and he suggested that I should follow the steps and in creating a virtual host as shown here
![screen shot 2017-05-13 at 4 44 06 pm](https://cloud.githubusercontent.com/assets/28006938/26025553/828a159e-37fb-11e7-8769-e8fd8b8df21d.png)

however, this is what I have in my htdocs 
![screen shot 2017-05-13 at 4 46 49 pm](https://cloud.githubusercontent.com/assets/28006938/26025577/203b5794-37fc-11e7-9ae1-e6c25fa9c9ea.png)

so what should I copy from the htdocs? and do I copy it in here?
![screen shot 2017-05-13 at 4 48 12 pm](https://cloud.githubusercontent.com/assets/28006938/26025585/38c499ec-37fc-11e7-8dde-a626ef4ec43d.png)

Thank you so much.

**Comment by jimver04** [comment]
Hi JA, 
virtual hosts is used for having multiple domain names in one machine which I guess it is not your case where you want the site to run localy.

In your mail, in the last screen, write in the url address field: http://127.0.0.1
a) if you get something then your apache server is up and running the index.php file
      b) else if you have changed the port to 8080 then write http://127.0.0.1:8080
c) download, uncompress MyoWebToolkit in htdocs in a folder named as "MyoWebToolkit" (remove master from the github folder name)
d) then write in url 
http://127.0.0.1/MyoWebToolkit/  
in order to run (Simulation) MyoWebToolkit/index.html   

Let me know,
Dimitrios

**Comment by jwaaherr** [comment]
I have tried it and it works perfectly now. Thank you so much for your efforts, I really appreciate it. 

Best regards,
Jawaher

**Comment by shradhasinghvi95** [comment]
Hi I have downloaded the myo webtoolkit but the link given doesnt work on chrome. 
going through the above suggestions when i tried opening port 3000 it takes me to apache dashboard. 
apache and node.js is running and it shows listening to *3000 on command prompt screen. 
Can i please get a help on how to run this ?
